import { ProtocolService } from "./protocol/protocol.service";
import { NetworkService } from "./network/network.service";
import { ERC20Service } from "./erc20/erc20.service";
import { LendingService } from "./lending/lending.service";
import { FarmingService } from "./farming/farming.service";
import { PoolingService } from "./pooling/pooling.service";
import { InvestService } from "./invest/invest.service";
import { PriceService } from "./price/price.service";
import { StatisticsService } from "./statistics/statistics.service";
import { ClaimService } from "./claiming/claiming.service";
import { EventService } from "./events/event.service";
import { ExitService } from "./exit/exit.service";
import { DefiHubConfig } from "./defihub.config";
import { CompanyService } from "./company/company.service";
export declare class DefihubModule {
    private readonly _config;
    private readonly _protocols;
    private readonly _companies;
    private readonly _networks;
    private readonly _erc20;
    private readonly _lending;
    private readonly _farming;
    private readonly _pooling;
    private readonly _invest;
    private readonly _exit;
    private readonly _prices;
    private readonly _statistics;
    private readonly _claiming;
    private readonly _events;
    constructor(config?: DefiHubConfig);
    protocols(): ProtocolService;
    companies(): CompanyService;
    networks(): NetworkService;
    erc20(): ERC20Service;
    events(): EventService;
    pooling(): PoolingService;
    farming(): FarmingService;
    lending(): LendingService;
    invest(): InvestService;
    exit(): ExitService;
    prices(): PriceService;
    statistics(): StatisticsService;
    claiming(): ClaimService;
}
